hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/urls.py
# hotel_your_choice/urls.py

from django.urls import path
from .views import (
    view_hotels, hotel_manager_dashboard, add_hotel,
    manage_bookings, book_hotel, client_dashboard,
    rate_experience, system_overview, manage_users,
    troubleshoot, register_view, login_view,
    logout_view, password_reset_view, unsubscribe_view
)

app_name = 'hotel_your_choice'

urlpatterns = [
    # Common URLs
    path('view-hotels/', view_hotels, name='view_hotels'),

    # Hotel Manager URLs
    path('hotel-manager/dashboard/', hotel_manager_dashboard, name='hotel_manager_dashboard'),
    path('hotel-manager/add-hotel/', add_hotel, name='add_hotel'),
    path('hotel-manager/manage-bookings/', manage_bookings, name='manage_bookings'),

    # Client URLs
    path('client/book-hotel/<int:hotel_id>/', book_hotel, name='book_hotel'),
    path('client/dashboard/', client_dashboard, name='client_dashboard'),
    path('client/rate-experience/<int:booking_id>/', rate_experience, name='rate_experience'),

    # Site Administrator URLs
    path('site-administrator/system-overview/', system_overview, name='system_overview'),
    path('site-administrator/manage-users/', manage_users, name='manage_users'),
    path('site-administrator/troubleshoot/', troubleshoot, name='troubleshoot'),

    # Authentication and Authorization URLs
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('password-reset/', password_reset_view, name='password_reset'),
    path('unsubscribe/', unsubscribe_view, name='unsubscribe'),
]

hotels_booking/backups/Backup_2023-12-02_v1/hotels_booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from hotel_your_choice.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hotel_your_choice/', include('hotel_your_choice.urls', namespace='hotel_your_choice')),
    path('', home, name='home'),
]

# Serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotels_booking/hotel_your_choice/urls.py
# urls.py

from django.urls import path, include
from django.contrib import admin
from hotel_your_choice import views
from .views import CustomPasswordResetConfirmView, CustomPasswordResetView, delete_comment, reschedule_booking, cancel_booking
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views 
from django.contrib.auth.views import PasswordResetDoneView
from .views import view_hotels, generate_excel, manage_bookings

# hotels_booking/hotel_your_choice/urls.py

app_name = 'hotel_your_choice'

urlpatterns = [

    # Redirect the root path to view-hotels
    path('', views.view_hotels, name='home'),


    # Common User URLs
    
    path('delete-experience/<int:booking_id>/', views.delete_experience, name='delete_experience'),
    path('add-comment/<int:booking_id>/', views.add_comment, name='add_comment'),
    path('delete_comment/<int:comment_id>/', delete_comment, name='delete_comment'),
    path('like-comment/<int:comment_id>/', views.like_comment, name='like_comment'),
    path('dislike-comment/<int:comment_id>/', views.dislike_comment, name='dislike_comment'),
    path('view-hotels/', views.view_hotels, name='view_hotels'),

    # Hotel Manager URLs
    path('hotel-manager/', include([
        path('dashboard/', views.hotel_manager_dashboard, name='hotel_manager_dashboard'),
        path('hotel-manager/add-hotel/', views.add_hotel, name='add_hotel'),
        path('hotel-manager/manage-bookings/', manage_bookings, name='manage_bookings'),
        path('hotel-manager/manage-bookings/download/', generate_excel, name='download_excel'),
        path('view-booking-details/<int:booking_id>/', views.view_booking_details, name='view_booking_details'),
        
        # Add other hotel manager URLs as needed
    ])),

    # Client URLs
    path('client/', include([
        path('dashboard/', views.client_dashboard, name='client_dashboard'),
        path('book-hotel/<int:hotel_id>/', views.book_hotel, name='book_hotel'),
        path('client/hotel_your_choice/reschedule-booking/<int:booking_id>/', reschedule_booking, name='reschedule_booking'),
        path('cancel-booking/<int:booking_id>/', cancel_booking, name='cancel_booking'),
        path('rate-experience/<int:booking_id>/', views.rate_experience, name='rate_experience'),
        path('view-ratings/', views.view_user_ratings, name='view_ratings'),
        # Add other client URLs as needed
    ])),

    # Site Administrator URLs
    path('site-administrator/', include([
        path('system-overview/', views.system_overview, name='system_overview'),
        path('manage-users/', views.manage_users, name='manage_users'),
        path('troubleshoot/', views.troubleshoot, name='troubleshoot'),
        # Add other site administrator URLs as needed
    ])),

    # Authentication and Authorization URLs
    path('auth/', include([
        path('register/', views.register_view, name='register'),
        path('login/', views.login_view, name='login'),
        path('logout/', views.logout_view, name='logout'),
        path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
        path('unsubscribe/', views.unsubscribe_view, name='unsubscribe'),
    ])),
    
    # Admin URLs
    path('admin/', admin.site.urls),

    # Add API endpoints
    path('api/user_statistics/', views.get_analytics_data, name='user_statistics'),
   
    # Additional URLs for managing users (custom views from your existing views.py)
    path('api/user_data/', views.get_user_data, name='get_user_data'),
    path('api/update_permissions/<int:user_id>/', views.update_permissions, name='update_permissions'),
    path('api/delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('api/view_user_logs/<int:user_id>/', views.view_user_logs, name='view_user_logs'),
    path('api/add_user/', views.add_user, name='add_user'),
    path('api/approve_ratings/<int:rating_id>/', views.approve_ratings, name='approve_ratings'),
    path('api/view_user_ratings/<int:user_id>/', views.view_user_ratings, name='view_user_ratings'),
    path('api/user_activities/<int:user_id>/', views.load_user_activities, name='load_user_activities'),
    # Add other URL patterns as needed
    

    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotels_booking/hotels_booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  # Add this import
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel_your_choice.urls')),
    # Include authentication URLs
    path('auth/', include('django.contrib.auth.urls')),
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/models.py
# hotel_your_choice/models.py

from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.conf import settings

class CustomUser(AbstractUser):
    profile_picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    is_hotel_manager = models.BooleanField(default=False)
    is_client_user = models.BooleanField(default=False)
    is_administrator = models.BooleanField(default=False)

    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to.',
        related_name='customuser_set',
        related_query_name='user',
    )

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='customuser_set',
        related_query_name='user',
    )

    def __str__(self):
        return self.username


class Hotel(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    address = models.CharField(max_length=255)
    managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='managed_hotels', blank=True)

    def __str__(self):
        return self.name


class Room(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_number = models.CharField(max_length=10)
    capacity = models.IntegerField()

    def __str__(self):
        return f'{self.hotel.name} - Room {self.room_number}'


class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, null=True)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    guests = models.PositiveIntegerField()
    issued_date = models.DateField(auto_now_add=True)
    rating = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.user.username} - {self.hotel.name} Booking'

    def save(self, *args, **kwargs):
        if not self.hotel_id:
            default_hotel_id = 1  # Replace with your default hotel ID
            self.hotel_id = default_hotel_id

        super().save(*args, **kwargs)

hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/forms.py
# hotel_your_choice/forms.py

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import CustomUser, Hotel

class YourBookingForm(forms.Form):
    hotel = forms.ModelChoiceField(queryset=Hotel.objects.all(), label='Select a Hotel')
    check_in = forms.DateField()
    check_out = forms.DateField()
    guests = forms.IntegerField()

class HotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = ['name', 'description', 'address']

class CustomRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    contact_number = forms.CharField(max_length=15, required=True)

    is_hotel_manager = forms.BooleanField(required=False)
    is_client_user = forms.BooleanField(required=False)
    is_administrator = forms.BooleanField(required=False)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'contact_number', 'password1', 'password2', 'is_hotel_manager', 'is_client_user', 'is_administrator']

hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/views.py
# hotel_your_choice/views.py

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import F, Window
from django.db.models.functions import RowNumber
from .models import Hotel, Booking, CustomUser
from .forms import YourBookingForm, CustomRegistrationForm, HotelForm
import logging
from django.contrib.auth import login, logout

logger = logging.getLogger(__name__)

# Common Views
def view_hotels(request):
    hotels = Hotel.objects.all()
    return render(request, 'hotel_your_choice/view_hotels.html', {'hotels': hotels})

# Hotel Manager Views
@login_required
def hotel_manager_dashboard(request):
    bookings = Booking.objects.filter(hotel__managers=request.user)
    return render(request, 'hotel_your_choice/hotel_manager/dashboard.html', {'bookings': bookings})

@login_required
def add_hotel(request):
    if request.method == 'POST':
        form = HotelForm(request.POST)
        if form.is_valid():
            hotel = form.save(commit=False)
            hotel.save()
            hotel.managers.add(request.user)
            messages.success(request, "Hotel added/updated successfully.")
            return redirect('hotel_your_choice:hotel_manager_dashboard')
    else:
        form = HotelForm()

    return render(request, 'hotel_your_choice/hotel_manager/add_hotel.html', {'form': form})

@login_required
def manage_bookings(request):
    bookings = Booking.objects.filter(hotel__managers=request.user)
    return render(request, 'hotel_your_choice/hotel_manager/manage_bookings.html', {'bookings': bookings})

# Client Views
@login_required
def book_hotel(request, hotel_id):
    available_hotels = Hotel.objects.all()

    if request.method == 'POST':
        form = YourBookingForm(request.POST)
        if form.is_valid():
            selected_hotel_id = form.cleaned_data['hotel'].id
            selected_hotel = get_object_or_404(Hotel, pk=selected_hotel_id)

            check_in_date = form.cleaned_data['check_in']
            check_out_date = form.cleaned_data['check_out']
            guests = form.cleaned_data['guests']

            Booking.objects.create(
                user=request.user,
                hotel=selected_hotel,
                check_in_date=check_in_date,
                check_out_date=check_out_date,
                guests=guests
            )

            messages.success(request, "Booking created successfully.")
            return redirect('hotel_your_choice:client_dashboard')
    else:
        form = YourBookingForm()

    return render(request, 'hotel_your_choice/client/book_hotel.html', {'form': form, 'available_hotels': available_hotels, 'selected_hotel_id': hotel_id})

@login_required
def client_dashboard(request):
    bookings = Booking.objects.filter(user=request.user)
    return render(request, 'hotel_your_choice/client/client_dashboard.html', {'bookings': bookings})

@login_required
def rate_experience(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)

    if request.method == 'POST':
        rating = request.POST.get('rating')
        booking.rating = rating
        booking.save()

        messages.success(request, "Rating submitted successfully.")
        return redirect('hotel_your_choice:client_dashboard')

    return render(request, 'hotel_your_choice/client/rate_experience.html', {'booking': booking})

# Site Administrator Views
def get_analytics_data():
    # Replace this with your actual logic to fetch analytics data
    return {'total_bookings': 100, 'revenue': 5000, 'average_rating': 4.5}

@login_required
def system_overview(request):
    # Assuming analytics is a variable or function you want to use in this view
    analytics = get_analytics_data()  # Replace with your actual logic to get analytics data
    return render(request, 'hotel_your_choice/system_overview.html', {'analytics': analytics})

@login_required
def manage_users(request):
    users = CustomUser.objects.all()
    return render(request, 'hotel_your_choice/site_administrator/manage_users.html', {'users': users})

@login_required
def troubleshoot(request):
    # Implement logic for troubleshooting
    return render(request, 'hotel_your_choice/site_administrator/troubleshoot.html')

# Authentication and Authorization Views
def register_view(request):
    if request.method == 'POST':
        form = CustomRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            messages.success(request, f"Welcome, {user.username}! You are now registered.")
            return redirect('hotel_your_choice:view_hotels')
        else:
            messages.error(request, "Registration failed. Please correct the errors in the form.")
    else:
        form = CustomRegistrationForm()

    return render(request, 'hotel_your_choice/authentication/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, f"Welcome, {user.username}!")
            return redirect('hotel_your_choice:view_hotels')
        else:
            messages.error(request, "Login failed. Please check your credentials.")
    else:
        form = AuthenticationForm()

    return render(request, 'hotel_your_choice/authentication/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('hotel_your_choice:view_hotels')

def password_reset_view(request):
    # Implement logic for password reset
    return render(request, 'hotel_your_choice/authentication/password_reset.html')

def unsubscribe_view(request):
    # Implement logic for user unsubscribe
    return render(request, 'hotel_your_choice/authentication/unsubscribe.html')

hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/templates/hotel_your_choice/book_hotel.html
{% extends 'base_generic.html' %}

{% block content %}
<h2>Book a Hotel</h2>
<!-- Your booking form goes here -->
<form method="post" action="{% url 'hotel_your_choice:book_hotel' hotel_id=selected_hotel_id %}" id="bookHotelForm">
    {% csrf_token %}
    <!-- Add a hidden input field to store the selected hotel ID -->
    <input type="hidden" name="selected_hotel_id" value="{{ selected_hotel_id }}">
    <label for="hotel">Select a Hotel:</label>
    <select name="hotel" id="hotel" required>
        {% for hotel in available_hotels %}
        <option value="{{ hotel.id }}">{{ hotel.name }}</option>
        {% endfor %}
    </select>

    <!-- Form fields go here -->
    <label for="check_in">Check-in date:</label>
    <input type="date" name="check_in" id="check_in" required>
    <label for="check_out">Check-out date:</label>
    <input type="date" name="check_out" id="check_out" required>
    <label for="guests">Number of guests:</label>
    <input type="number" name="guests" id="guests" required>
    <button type="submit">Book Now</button>
</form>
{% endblock %}

hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/templates/hotel_your_choice/dashboard.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Your Bookings</h1>

<!-- Booking stories table -->
<table class="booking-table">
    <thead>
        <tr>
            <th>Serial Number</th>
            <th>Hotel</th>
            <th>Check-in</th>
            <th>Check-out</th>
            <th>Guests</th>
            <th>Issued Date</th> <!-- Replace with the correct field name -->
            <!-- Add other table headers as needed -->
        </tr>
    </thead>
    <tbody>
        {% for booking in filtered_bookings %}
        <tr>
            <td>{{ booking.row_number }}</td>
            <td>{{ booking.hotel.name }}</td>
            <td>{{ booking.check_in_date }}</td>
            <td>{{ booking.check_out_date }}</td>
            <td>{{ booking.guests }}</td>
            <td>{{ booking.issued_date }}</td><!-- Replace with the correct field name -->
            <!-- Add other table cells as needed -->
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/templates/hotel_your_choice/home.html
<!--hotels_booking\hotel_your_choice\templates\hotel_your_choice\<home class="html"-->

{% extends 'base_generic.html' %}

{% block content %}
<h1>Welcome to Your Hotel Booking Site</h1>
<p>Please <a href="{% url 'hotel_your_choice:login' %}">log in</a> to book a hotel.</p>
{% if available_hotels %}

<h2>Available Hotels</h2>
<ul>
    {% for hotel in available_hotels %}
    <li>{{ hotel.name }}</li>
    {% endfor %}
</ul>
{% else %}
<p>No hotels available.</p>
{% endif %}
{% endblock %}

hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/templates/hotel_your_choice/login.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="login-container">
    <h2>Login</h2>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <p style="color: red;">{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Your login form goes here -->
    <form method="post" action="{% url 'hotel_your_choice:login' %}" class="login-form">
        {% csrf_token %}
        <!-- Login form fields go here -->
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" autocomplete="username">

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" autocomplete="current-password">

        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/templates/hotel_your_choice/register.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="registration-container">
    <h2>Register</h2>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}

    {% if form.errors %}
    <div class="alert alert-danger">
        <strong>Error!</strong> Please correct the following errors:
        <ul>
            {% for field, errors in form.errors.items %}
            {% for error in errors %}
            <li>{{ field }}: {{ error }}</li>
            {% endfor %}
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <form method="post" action="{% url 'hotel_your_choice:register' %}" class="registration-form">
        {% csrf_token %}

        <!-- Existing form fields -->
        <label for="{{ form.email.id_for_label }}">Email:</label>
        {{ form.email }}
        <br>

        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}
        <br>

        <label for="{{ form.first_name.id_for_label }}">First Name:</label>
        {{ form.first_name }}
        <br>

        <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
        {{ form.last_name }}
        <br>

        <label for="{{ form.contact_number.id_for_label }}">Contact Number:</label>
        {{ form.contact_number }}
        <br>

        <label for="{{ form.password1.id_for_label }}">Password:</label>
        {{ form.password1 }}
        <br>

        <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
        {{ form.password2 }}
        <br>

        <!-- New registration options checkboxes -->
        <label for="{{ form.is_hotel_manager.id_for_label }}">
            {{ form.is_hotel_manager }} Is Hotel Manager
        </label>
        <br>

        <label for="{{ form.is_client_user.id_for_label }}">
            {{ form.is_client_user }} Is Client User
        </label>
        <br>

        <label for="{{ form.is_administrator.id_for_label }}">
            {{ form.is_administrator }} Is Administrator
        </label>
        <br>

        <button type="submit">Register</button>
    </form>
</div>
{% endblock %}

hotels_booking/backups/Backup_2023-12-02_v1/hotel_your_choice/templates/hotel_your_choice/success.html
<!-- hotel_your_choice/templates/hotel_your_choice/success.html -->

<!DOCTYPE html>
<html>

    <head>
        <title>Login Success</title>
    </head>

    <body>
        <h1>Login Successful</h1>
        <!-- Add any additional content as needed -->
    </body>

</html>